-- ============================================================
-- Yummi Glu Glu — 20 recetas originarias de VENEZUELA 🇻🇪
-- Distribución pareja por etapa:
--   INICIO (6-11m):       7 recetas — ingredientes únicos venezolanos (apio criollo, lechosa, jojoto, ñame)
--   TRANSICION (12-23m):  7 recetas — clásicos venezolanos (cachapa, perico, pisillo, hervido)
--   PREESCOLAR (24m+):    6 recetas — platos icónicos baby (pabellón, arepa rellena, hallaca, tequeños)
--
-- Todas FREE, sin sal ni azúcar agregada (donde aplica).
-- Idempotente: ON CONFLICT (slug) DO NOTHING.
-- Tags: 'venezuela' + 'latam' + categorías específicas.
-- ============================================================

-- ─── INICIO (6-11m) ──────────────────────────────────────────

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('atol-yuca-venezuela', 'Atol de yuca venezolano', 'Bebida tibia y espesa con yuca rallada y panela. Tradicional del campo venezolano para los más pequeños.', ARRAY['desayuno','snack'], ARRAY['inicio'], 18, 2, ARRAY[]::text[], 125, 1.5, 30, 0.4, 0.7,
'[{"id":"yuca","nombre":"Yuca tierna","cantidad":100,"unidad":"g","calorias_por_100g":160},{"id":"panela","nombre":"Panela rallada","cantidad":10,"unidad":"g","calorias_por_100g":380},{"id":"agua","nombre":"Agua","cantidad":250,"unidad":"ml","calorias_por_100g":0},{"id":"canela","nombre":"Canela en rama","cantidad":1,"unidad":"trozo","calorias_por_100g":247}]'::jsonb,
'[{"orden":1,"descripcion":"Pela la yuca, retira el hilo central y rállala fina.","duracion_min":4},{"orden":2,"descripcion":"Cocina la yuca rallada con el agua y la canela durante 12 minutos revolviendo.","duracion_min":12},{"orden":3,"descripcion":"Cuando espese, agrega la panela rallada y revuelve hasta disolver.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','atol','bebida','yuca','tradicional'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('crema-apio-venezuela', 'Crema de apio criollo venezolano', 'Crema suave de apio criollo, tubérculo venezolano único (no confundir con apio rama). Sabor a tierra fresca.', ARRAY['almuerzo','cena'], ARRAY['inicio'], 22, 2, ARRAY[]::text[], 95, 2, 20, 0.4, 0.5,
'[{"id":"apio-criollo","nombre":"Apio criollo (arracacha de la zona)","cantidad":180,"unidad":"g","calorias_por_100g":85},{"id":"papa","nombre":"Papa","cantidad":50,"unidad":"g","calorias_por_100g":77},{"id":"agua","nombre":"Agua","cantidad":200,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Pela el apio criollo y la papa, córtalos en cubos pequeños.","duracion_min":4},{"orden":2,"descripcion":"Cocínalos juntos en agua durante 18 minutos hasta estar muy tiernos.","duracion_min":18},{"orden":3,"descripcion":"Procesa con el agua de cocción hasta obtener una crema suave y aromática.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','apio-criollo','tuberculo','tradicional','vegetariano'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('compota-lechosa-pina-venezuela', 'Compota de lechosa con piña', 'Compota tropical con lechosa (papaya venezolana) y piña dulce. Rica en enzimas que favorecen la digestión.', ARRAY['snack','desayuno'], ARRAY['inicio'], 12, 2, ARRAY[]::text[], 85, 1, 21, 0.3, 0.3,
'[{"id":"lechosa","nombre":"Lechosa (papaya) madura","cantidad":150,"unidad":"g","calorias_por_100g":43},{"id":"pina","nombre":"Piña madura","cantidad":80,"unidad":"g","calorias_por_100g":50},{"id":"limon","nombre":"Jugo de limón","cantidad":3,"unidad":"gotas","calorias_por_100g":29}]'::jsonb,
'[{"orden":1,"descripcion":"Pela la lechosa, retira las semillas negras y córtala en cubos pequeños.","duracion_min":3},{"orden":2,"descripcion":"Pela y corta la piña en trocitos pequeños.","duracion_min":3},{"orden":3,"descripcion":"Cocina ambas frutas tapado a fuego bajo durante 6 minutos.","duracion_min":6},{"orden":4,"descripcion":"Procesa hasta lograr una compota suave y agrega 3 gotas de limón.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','tropical','lechosa','pina','sin-azucar'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('papilla-platano-maduro-avena-venezuela', 'Papilla de plátano maduro con avena', 'Papilla cremosa con plátano maduro venezolano y avena suave. Dulzura natural sin azúcar.', ARRAY['desayuno','snack'], ARRAY['inicio'], 12, 2, ARRAY['gluten','lactosa']::text[], 155, 4.5, 32, 2, 1.4,
'[{"id":"platano-maduro","nombre":"Plátano maduro grande","cantidad":1,"unidad":"unidad","calorias_por_100g":89},{"id":"avena","nombre":"Avena en hojuelas","cantidad":25,"unidad":"g","calorias_por_100g":389},{"id":"leche","nombre":"Leche","cantidad":120,"unidad":"ml","calorias_por_100g":61}]'::jsonb,
'[{"orden":1,"descripcion":"Pela el plátano maduro y aplástalo con un tenedor.","duracion_min":2},{"orden":2,"descripcion":"Cocina la avena con la leche a fuego bajo durante 8 minutos revolviendo.","duracion_min":8},{"orden":3,"descripcion":"Mezcla el plátano aplastado con la avena tibia hasta integrar.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','platano-maduro','avena','desayuno','dulce-natural'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('pure-auyama-leche-vainilla-venezuela', 'Puré de auyama con leche y vainilla', 'Puré sedoso de auyama venezolana cocida con leche y un toque de vainilla. Reconfortante y dulce.', ARRAY['almuerzo','cena'], ARRAY['inicio'], 20, 2, ARRAY['lactosa']::text[], 105, 3.5, 19, 1.5, 0.7,
'[{"id":"auyama","nombre":"Auyama (calabaza venezolana)","cantidad":180,"unidad":"g","calorias_por_100g":26},{"id":"leche","nombre":"Leche entera","cantidad":80,"unidad":"ml","calorias_por_100g":61},{"id":"vainilla","nombre":"Esencia de vainilla","cantidad":3,"unidad":"gotas","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Pela la auyama y córtala en cubos pequeños.","duracion_min":3},{"orden":2,"descripcion":"Cocínala al vapor durante 15 minutos hasta estar bien tierna.","duracion_min":15},{"orden":3,"descripcion":"Procesa con la leche tibia y las gotas de vainilla hasta obtener un puré sedoso.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','auyama','calabaza','vegetariano','dulce-natural'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('compota-nispero-manzana-venezuela', 'Compota de níspero con manzana', 'Compota con níspero venezolano, fruta dulce y aromática del oriente del país, junto con manzana.', ARRAY['snack','desayuno'], ARRAY['inicio'], 15, 2, ARRAY[]::text[], 90, 0.8, 22, 0.3, 0.4,
'[{"id":"nispero","nombre":"Níspero maduro","cantidad":100,"unidad":"g","calorias_por_100g":47},{"id":"manzana","nombre":"Manzana","cantidad":1,"unidad":"unidad","calorias_por_100g":52},{"id":"agua","nombre":"Agua","cantidad":50,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Pela los nísperos, retira las semillas y córtalos en trocitos.","duracion_min":4},{"orden":2,"descripcion":"Pela y corta la manzana en cubos pequeños.","duracion_min":2},{"orden":3,"descripcion":"Cocina ambas frutas con el agua durante 10 minutos.","duracion_min":10},{"orden":4,"descripcion":"Procesa hasta obtener una compota suave y cuela si quedan partes duras.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','tropical','nispero','fruta','sin-azucar'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('crema-jojoto-coco-venezuela', 'Crema de jojoto con coco', 'Crema venezolana de jojoto (maíz tierno) con leche de coco. Sabor del Caribe en cada cucharada.', ARRAY['almuerzo','snack'], ARRAY['inicio'], 18, 2, ARRAY[]::text[], 120, 3, 22, 3, 0.7,
'[{"id":"jojoto","nombre":"Jojoto (maíz tierno) desgranado","cantidad":150,"unidad":"g","calorias_por_100g":86},{"id":"leche-coco","nombre":"Leche de coco","cantidad":80,"unidad":"ml","calorias_por_100g":230},{"id":"agua","nombre":"Agua","cantidad":100,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Cocina los granos de jojoto en agua durante 10 minutos hasta estar tiernos.","duracion_min":10},{"orden":2,"descripcion":"Procesa el jojoto con la leche de coco hasta obtener una crema dorada.","duracion_min":3},{"orden":3,"descripcion":"Devuelve la crema a la olla y cocina 5 minutos más para integrar sabores.","duracion_min":5}]'::jsonb,
ARRAY['venezuela','latam','jojoto','coco','caribe','vegetariano'], false, true)
ON CONFLICT (slug) DO NOTHING;

-- ─── TRANSICION (12-23m) ─────────────────────────────────────

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('cachapa-baby-queso-mano', 'Cachapa baby con queso de mano', 'Cachapa venezolana en miniatura: panqueque grande y fino de jojoto con queso de mano por dentro y mantequilla.', ARRAY['desayuno','snack'], ARRAY['transicion'], 25, 3, ARRAY['lactosa','huevo']::text[], 225, 9, 30, 8, 1.2,
'[{"id":"jojoto","nombre":"Jojoto (maíz tierno) desgranado","cantidad":250,"unidad":"g","calorias_por_100g":86},{"id":"queso-mano","nombre":"Queso de mano fresco","cantidad":60,"unidad":"g","calorias_por_100g":264},{"id":"huevo","nombre":"Huevo","cantidad":1,"unidad":"unidad","calorias_por_100g":155},{"id":"leche","nombre":"Leche","cantidad":50,"unidad":"ml","calorias_por_100g":61},{"id":"mantequilla","nombre":"Mantequilla","cantidad":10,"unidad":"g","calorias_por_100g":717}]'::jsonb,
'[{"orden":1,"descripcion":"Procesa el jojoto con la leche y el huevo hasta lograr una mezcla líquida espesa.","duracion_min":3},{"orden":2,"descripcion":"Calienta una sartén grande con mantequilla a fuego medio.","duracion_min":2},{"orden":3,"descripcion":"Vierte la mezcla formando un círculo grande y fino. Cocina 4 minutos hasta dorar.","duracion_min":4},{"orden":4,"descripcion":"Voltea con una espátula, agrega queso de mano en una mitad y dobla a la mitad cubriendo el queso.","duracion_min":4}]'::jsonb,
ARRAY['venezuela','latam','cachapa','iconico','jojoto','queso-mano','tradicional'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('sopa-platano-verde-venezuela', 'Sopa de plátano verde venezolana', 'Sopa cremosa con plátano verde rallado, caldo de pollo casero y un toque de cilantro. Tradicional venezolana.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 30, 3, ARRAY[]::text[], 175, 12, 22, 4, 1.3,
'[{"id":"platano-verde","nombre":"Plátano verde","cantidad":1,"unidad":"unidad","calorias_por_100g":89},{"id":"pollo","nombre":"Muslo de pollo deshuesado","cantidad":80,"unidad":"g","calorias_por_100g":165},{"id":"cebolla","nombre":"Cebolla","cantidad":30,"unidad":"g","calorias_por_100g":40},{"id":"cilantro","nombre":"Cilantro","cantidad":2,"unidad":"hojas","calorias_por_100g":23},{"id":"agua","nombre":"Agua","cantidad":500,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Hierve el pollo con cebolla en el agua durante 15 minutos.","duracion_min":15},{"orden":2,"descripcion":"Pela el plátano verde y rállalo con un rallador fino.","duracion_min":4},{"orden":3,"descripcion":"Agrega el plátano rallado al caldo y cocina 10 minutos hasta espesar.","duracion_min":10},{"orden":4,"descripcion":"Desmenuza el pollo en hebras y devuélvelo a la sopa con cilantro picado.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','sopa','platano-verde','tradicional','pollo'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('pisillo-pollo-suave-venezuela', 'Pisillo de pollo suave venezolano', 'Pollo deshilachado (mechado) y guisado al estilo venezolano con cebolla, tomate y ají dulce SIN picante.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 35, 3, ARRAY[]::text[], 195, 22, 8, 8, 1.5,
'[{"id":"pollo","nombre":"Pechuga de pollo","cantidad":180,"unidad":"g","calorias_por_100g":165},{"id":"cebolla","nombre":"Cebolla","cantidad":50,"unidad":"g","calorias_por_100g":40},{"id":"tomate","nombre":"Tomate","cantidad":80,"unidad":"g","calorias_por_100g":18},{"id":"aji-dulce","nombre":"Ají dulce (sin picante)","cantidad":20,"unidad":"g","calorias_por_100g":28},{"id":"aceite","nombre":"Aceite","cantidad":8,"unidad":"ml","calorias_por_100g":884},{"id":"cilantro","nombre":"Cilantro","cantidad":2,"unidad":"hojas","calorias_por_100g":23}]'::jsonb,
'[{"orden":1,"descripcion":"Hierve el pollo en agua durante 20 minutos hasta estar bien cocido.","duracion_min":20},{"orden":2,"descripcion":"Sácalo, deja entibiar y desmenúzalo en hebras muy finas (mecharlo) con las manos o dos tenedores.","duracion_min":5},{"orden":3,"descripcion":"Aparte, dora cebolla, tomate y ají dulce picados muy fino en aceite.","duracion_min":6},{"orden":4,"descripcion":"Mezcla el pollo mechado con el guiso y cocina 4 minutos más con cilantro al final.","duracion_min":4}]'::jsonb,
ARRAY['venezuela','latam','pisillo','mechado','tradicional','pollo','aji-dulce'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('perico-baby-venezuela', 'Perico baby venezolano', 'Huevo revuelto al estilo venezolano con cebolla, tomate y ají dulce. Desayuno tradicional sin picante.', ARRAY['desayuno','almuerzo'], ARRAY['transicion'], 12, 1, ARRAY['huevo']::text[], 175, 13, 8, 11, 2,
'[{"id":"huevos","nombre":"Huevos","cantidad":2,"unidad":"unidades","calorias_por_100g":155},{"id":"cebolla","nombre":"Cebolla","cantidad":30,"unidad":"g","calorias_por_100g":40},{"id":"tomate","nombre":"Tomate","cantidad":60,"unidad":"g","calorias_por_100g":18},{"id":"aji-dulce","nombre":"Ají dulce","cantidad":15,"unidad":"g","calorias_por_100g":28},{"id":"aceite","nombre":"Aceite","cantidad":5,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Pica cebolla, tomate y ají dulce muy finos.","duracion_min":3},{"orden":2,"descripcion":"Dora la cebolla en aceite, agrega tomate y ají dulce, cocina 4 minutos.","duracion_min":4},{"orden":3,"descripcion":"Bate los huevos aparte y agrégalos al guiso.","duracion_min":2},{"orden":4,"descripcion":"Revuelve constantemente hasta que los huevos cuajen pero queden cremosos.","duracion_min":3}]'::jsonb,
ARRAY['venezuela','latam','perico','iconico','desayuno','huevo','tradicional'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('arroz-caraotas-venezuela', 'Arroz con caraotas negras', 'Plato tradicional venezolano: arroz blanco esponjoso con caraotas (frijoles negros) suaves y aromáticas.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 35, 3, ARRAY[]::text[], 245, 11, 48, 2.5, 3,
'[{"id":"caraotas","nombre":"Caraotas (frijoles negros) cocidas","cantidad":120,"unidad":"g","calorias_por_100g":132},{"id":"arroz","nombre":"Arroz blanco","cantidad":80,"unidad":"g","calorias_por_100g":130},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"aji-dulce","nombre":"Ají dulce","cantidad":15,"unidad":"g","calorias_por_100g":28},{"id":"aceite","nombre":"Aceite","cantidad":5,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Cocina el arroz con el doble de agua hasta absorber, unos 18 minutos.","duracion_min":18},{"orden":2,"descripcion":"En otra olla dora cebolla y ají dulce picados con aceite.","duracion_min":5},{"orden":3,"descripcion":"Agrega las caraotas ya cocidas con un poco de su caldo y cocina 8 minutos.","duracion_min":8},{"orden":4,"descripcion":"Sirve el arroz al lado de las caraotas en un plato.","duracion_min":2}]'::jsonb,
ARRAY['venezuela','latam','arroz-caraotas','tradicional','caraotas','frijoles-negros'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('bollo-pelon-light-venezuela', 'Bollo pelón light venezolano', 'Bola de masa de maíz precocida rellena de guiso de pollo, cocida al vapor. Plato típico de Aragua.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 45, 3, ARRAY[]::text[], 230, 13, 38, 4, 1.4,
'[{"id":"harina-maiz","nombre":"Harina de maíz precocida","cantidad":120,"unidad":"g","calorias_por_100g":366},{"id":"pollo","nombre":"Pechuga de pollo cocida","cantidad":80,"unidad":"g","calorias_por_100g":165},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"tomate","nombre":"Tomate","cantidad":50,"unidad":"g","calorias_por_100g":18},{"id":"agua","nombre":"Agua tibia","cantidad":150,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Prepara el guiso: dora cebolla y tomate picados, agrega pollo desmenuzado, cocina 5 minutos.","duracion_min":7},{"orden":2,"descripcion":"Mezcla la harina de maíz con agua tibia hasta formar una masa suave.","duracion_min":5},{"orden":3,"descripcion":"Toma porciones de masa, abre un hueco con el pulgar y rellena con guiso. Cierra formando bola.","duracion_min":8},{"orden":4,"descripcion":"Cocina los bollos en agua hirviendo durante 25 minutos.","duracion_min":25}]'::jsonb,
ARRAY['venezuela','latam','bollo-pelon','aragua','tradicional','masa-maiz'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('hervido-pollo-name-venezuela', 'Hervido de pollo con ñame y mapuey', 'Hervido venezolano de pollo con tubérculos del Caribe: ñame, mapuey y batata. Caldo claro y nutritivo.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 50, 3, ARRAY[]::text[], 245, 18, 32, 5, 1.7,
'[{"id":"pollo","nombre":"Pollo en presa","cantidad":150,"unidad":"g","calorias_por_100g":165},{"id":"name","nombre":"Ñame","cantidad":80,"unidad":"g","calorias_por_100g":118},{"id":"mapuey","nombre":"Mapuey","cantidad":60,"unidad":"g","calorias_por_100g":108},{"id":"batata","nombre":"Batata venezolana","cantidad":50,"unidad":"g","calorias_por_100g":86},{"id":"jojoto","nombre":"Trozo de jojoto","cantidad":1,"unidad":"rodaja","calorias_por_100g":86},{"id":"cilantro","nombre":"Cilantro","cantidad":3,"unidad":"hojas","calorias_por_100g":23},{"id":"agua","nombre":"Agua","cantidad":600,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Cocina el pollo en agua con cilantro durante 25 minutos.","duracion_min":25},{"orden":2,"descripcion":"Pela ñame, mapuey y batata y córtalos en trozos medianos.","duracion_min":6},{"orden":3,"descripcion":"Agrega los tubérculos y la rodaja de jojoto, cocina 18 minutos hasta tiernos.","duracion_min":18},{"orden":4,"descripcion":"Desmenuza el pollo y sirve el caldo con todos los tubérculos blandos.","duracion_min":3}]'::jsonb,
ARRAY['venezuela','latam','hervido','name','mapuey','tradicional','caribe','pollo'], false, true)
ON CONFLICT (slug) DO NOTHING;

-- ─── PREESCOLAR (24m+) ───────────────────────────────────────

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('pabellon-criollo-baby', 'Pabellón criollo baby', 'Versión baby del plato bandera de Venezuela: caraotas negras, carne mechada suave, arroz blanco y plátano maduro caramelizado.', ARRAY['almuerzo'], ARRAY['preescolar'], 50, 3, ARRAY[]::text[], 365, 22, 50, 8, 3.8,
'[{"id":"caraotas","nombre":"Caraotas (frijoles negros) cocidas","cantidad":100,"unidad":"g","calorias_por_100g":132},{"id":"carne","nombre":"Falda de res","cantidad":120,"unidad":"g","calorias_por_100g":250},{"id":"arroz","nombre":"Arroz blanco cocido","cantidad":100,"unidad":"g","calorias_por_100g":130},{"id":"platano-maduro","nombre":"Plátano maduro","cantidad":0.5,"unidad":"unidad","calorias_por_100g":89},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"tomate","nombre":"Tomate","cantidad":50,"unidad":"g","calorias_por_100g":18},{"id":"aji-dulce","nombre":"Ají dulce","cantidad":15,"unidad":"g","calorias_por_100g":28}]'::jsonb,
'[{"orden":1,"descripcion":"Hierve la falda en agua durante 30 minutos. Sácala, deja entibiar y mécala (desmenuza en hebras finas).","duracion_min":32},{"orden":2,"descripcion":"Dora cebolla, tomate y ají dulce, agrega la carne mechada y cocina 8 minutos.","duracion_min":10},{"orden":3,"descripcion":"Hornea las rodajas de plátano maduro a 200°C durante 12 minutos hasta caramelizar.","duracion_min":12},{"orden":4,"descripcion":"Calienta las caraotas y sirve los 4 elementos juntos en el plato baby.","duracion_min":5}]'::jsonb,
ARRAY['venezuela','latam','pabellon-criollo','iconico','tradicional','plato-completo','plato-bandera'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('arepa-horno-queso-baby-venezuela', 'Arepa al horno rellena de queso baby', 'Arepa venezolana hecha con harina de maíz precocida, asada al horno y rellena con queso fresco. SIN sal añadida.', ARRAY['desayuno','snack','cena'], ARRAY['preescolar'], 25, 3, ARRAY['lactosa']::text[], 215, 8, 32, 6, 1.3,
'[{"id":"harina-maiz","nombre":"Harina de maíz precocida (harina pan)","cantidad":120,"unidad":"g","calorias_por_100g":366},{"id":"queso-fresco","nombre":"Queso blanco fresco","cantidad":60,"unidad":"g","calorias_por_100g":264},{"id":"agua","nombre":"Agua tibia","cantidad":180,"unidad":"ml","calorias_por_100g":0},{"id":"aceite","nombre":"Aceite","cantidad":3,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Mezcla la harina de maíz precocida con el agua tibia hasta formar una masa suave que no se pegue a las manos.","duracion_min":5},{"orden":2,"descripcion":"Forma bolitas y aplástalas en forma de disco grueso, untándolas con un poco de aceite.","duracion_min":4},{"orden":3,"descripcion":"Hornea las arepas a 200°C durante 15 minutos volteándolas a la mitad del tiempo.","duracion_min":15},{"orden":4,"descripcion":"Ábrelas con cuidado por un costado y rellénalas con queso fresco. Vuelve al horno 2 minutos para que el queso se derrita.","duracion_min":3}]'::jsonb,
ARRAY['venezuela','latam','arepa','iconico','tradicional','horneado','harina-pan'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('hallaca-baby-venezuela', 'Hallaca baby simplificada', 'Versión baby de la hallaca venezolana navideña: masa de maíz teñida con onoto, relleno de guiso suave, envuelta en hoja de plátano.', ARRAY['almuerzo','cena'], ARRAY['preescolar'], 90, 3, ARRAY[]::text[], 290, 14, 40, 8, 2.2,
'[{"id":"harina-maiz","nombre":"Harina de maíz precocida","cantidad":140,"unidad":"g","calorias_por_100g":366},{"id":"pollo","nombre":"Pollo cocido desmenuzado","cantidad":50,"unidad":"g","calorias_por_100g":165},{"id":"carne","nombre":"Carne magra picada","cantidad":50,"unidad":"g","calorias_por_100g":250},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"aji-dulce","nombre":"Ají dulce","cantidad":15,"unidad":"g","calorias_por_100g":28},{"id":"onoto","nombre":"Onoto (achiote)","cantidad":2,"unidad":"semillas","calorias_por_100g":350},{"id":"hoja-platano","nombre":"Hoja de plátano","cantidad":3,"unidad":"unidades","calorias_por_100g":0},{"id":"aceite","nombre":"Aceite","cantidad":10,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Calienta aceite con onoto hasta que tome color rojo-anaranjado intenso, retira las semillas.","duracion_min":3},{"orden":2,"descripcion":"Mezcla la harina de maíz con el aceite de onoto y agua tibia hasta formar masa amarilla suave.","duracion_min":6},{"orden":3,"descripcion":"Prepara el guiso: dora cebolla y ají dulce, agrega pollo y carne, cocina 10 minutos.","duracion_min":12},{"orden":4,"descripcion":"Arma cada hallaca: hoja, capa de masa amarilla, cucharada de guiso, cierra y ata. Cocina en agua hirviendo 60 minutos.","duracion_min":70}]'::jsonb,
ARRAY['venezuela','latam','hallaca','iconico','tradicional','navidad','onoto'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('tequenos-horno-baby-venezuela', 'Tequeños al horno baby', 'Versión saludable de los tequeños venezolanos: palitos de queso envueltos en masa suave y horneados (no fritos).', ARRAY['snack'], ARRAY['preescolar'], 35, 4, ARRAY['lactosa','huevo','gluten']::text[], 215, 11, 25, 7, 1,
'[{"id":"harina","nombre":"Harina","cantidad":120,"unidad":"g","calorias_por_100g":364},{"id":"queso-blanco","nombre":"Queso blanco duro (estilo paisa)","cantidad":150,"unidad":"g","calorias_por_100g":264},{"id":"mantequilla","nombre":"Mantequilla blanda","cantidad":25,"unidad":"g","calorias_por_100g":717},{"id":"huevo","nombre":"Huevo","cantidad":1,"unidad":"unidad","calorias_por_100g":155},{"id":"leche","nombre":"Leche","cantidad":40,"unidad":"ml","calorias_por_100g":61}]'::jsonb,
'[{"orden":1,"descripcion":"Mezcla harina con mantequilla, huevo y leche hasta formar una masa suave. Reposa 15 min.","duracion_min":18},{"orden":2,"descripcion":"Corta el queso en palitos pequeños del tamaño de un dedo de bebé.","duracion_min":4},{"orden":3,"descripcion":"Estira la masa fina y corta tiras. Envuelve cada palito de queso en una tira en espiral.","duracion_min":8},{"orden":4,"descripcion":"Coloca los tequeños en una bandeja y hornea a 200°C durante 15 minutos hasta dorar.","duracion_min":15}]'::jsonb,
ARRAY['venezuela','latam','tequenos','iconico','tradicional','horneado','queso'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('polvorosa-pollo-light-venezuela', 'Polvorosa de pollo light', 'Pastel venezolano de pollo guisado cubierto con masa quebrada de manteca y horneado. Versión liviana.', ARRAY['almuerzo','cena'], ARRAY['preescolar'], 60, 4, ARRAY['gluten','huevo','lactosa']::text[], 310, 18, 30, 13, 1.8,
'[{"id":"pollo","nombre":"Pollo cocido desmenuzado","cantidad":150,"unidad":"g","calorias_por_100g":165},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"tomate","nombre":"Tomate","cantidad":40,"unidad":"g","calorias_por_100g":18},{"id":"harina","nombre":"Harina","cantidad":120,"unidad":"g","calorias_por_100g":364},{"id":"mantequilla","nombre":"Mantequilla fría","cantidad":50,"unidad":"g","calorias_por_100g":717},{"id":"huevo","nombre":"Yema de huevo","cantidad":1,"unidad":"unidad","calorias_por_100g":155},{"id":"agua","nombre":"Agua helada","cantidad":30,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Prepara el guiso: dora cebolla y tomate, agrega pollo desmenuzado, cocina 8 minutos.","duracion_min":10},{"orden":2,"descripcion":"Mezcla harina con mantequilla fría usando dedos hasta lograr textura de arena. Agrega yema y agua.","duracion_min":8},{"orden":3,"descripcion":"Estira la masa y forra un molde. Vierte el guiso de pollo y cubre con otra capa de masa.","duracion_min":8},{"orden":4,"descripcion":"Hornea a 180°C durante 30 minutos hasta que la masa esté dorada.","duracion_min":30}]'::jsonb,
ARRAY['venezuela','latam','polvorosa','tradicional','pollo','horneado','pastel-salado'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('dulce-lechosa-baby-light-venezuela', 'Dulce de lechosa baby light', 'Versión saludable del dulce de lechosa venezolano: cocido a fuego lento con canela, clavo y muy poca panela.', ARRAY['snack'], ARRAY['preescolar'], 60, 4, ARRAY[]::text[], 100, 0.8, 25, 0.3, 0.4,
'[{"id":"lechosa","nombre":"Lechosa verde (papaya verde)","cantidad":300,"unidad":"g","calorias_por_100g":43},{"id":"panela","nombre":"Panela rallada","cantidad":25,"unidad":"g","calorias_por_100g":380},{"id":"canela","nombre":"Canela en rama","cantidad":1,"unidad":"rama","calorias_por_100g":247},{"id":"clavo","nombre":"Clavo de olor","cantidad":2,"unidad":"unidades","calorias_por_100g":274},{"id":"limon","nombre":"Cáscara de limón","cantidad":1,"unidad":"trozo","calorias_por_100g":29},{"id":"agua","nombre":"Agua","cantidad":400,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Pela la lechosa verde y córtala en tiras finas, retira semillas.","duracion_min":6},{"orden":2,"descripcion":"Cocínala en agua con cáscara de limón durante 15 minutos para suavizarla.","duracion_min":15},{"orden":3,"descripcion":"Escurre y devuelve a la olla con la panela, canela y clavo, agrega agua fresca.","duracion_min":3},{"orden":4,"descripcion":"Cocina a fuego bajo durante 35 minutos hasta que la lechosa esté translúcida y el almíbar denso.","duracion_min":35}]'::jsonb,
ARRAY['venezuela','latam','dulce-lechosa','postre','tradicional','sin-azucar-agregada'], false, true)
ON CONFLICT (slug) DO NOTHING;
