-- ============================================================
-- Yummi Glu Glu — 15 recetas originarias de MÉXICO 🇲🇽 (recetas 183-197)
-- Complementa las 5 ya cargadas (83-87: sopa fideos seca, frijoles olla, atole avena, caldo tlalpeño, quesadilla).
-- Total final México: 20 (7 inicio + 7 transición + 6 preescolar)
--
-- ¡ÚLTIMO PAÍS! Con esta migración el plan de 120 recetas originarias queda COMPLETO al 100%.
--
-- Todas FREE, sin chile picante ni sal añadida.
-- Idempotente: ON CONFLICT (slug) DO NOTHING.
-- Tags: 'mexico' + 'latam' + categorías específicas.
-- ============================================================

-- ─── INICIO (6-11m) — 5 nuevas ───────────────────────────────

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('atole-fresa-light-mexico', 'Atole de fresa light', 'Bebida tibia tradicional mexicana con fresas frescas y un toque de leche. Cremoso, sin azúcar agregada.', ARRAY['desayuno','snack'], ARRAY['inicio'], 15, 2, ARRAY['lactosa']::text[], 110, 4, 18, 2.5, 0.8,
'[{"id":"fresas","nombre":"Fresas maduras","cantidad":80,"unidad":"g","calorias_por_100g":32},{"id":"leche","nombre":"Leche entera","cantidad":250,"unidad":"ml","calorias_por_100g":61},{"id":"maicena","nombre":"Fécula de maíz","cantidad":10,"unidad":"g","calorias_por_100g":381},{"id":"vainilla","nombre":"Esencia de vainilla","cantidad":3,"unidad":"gotas","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Lava las fresas, retira los cabos y procésalas hasta hacerlas puré.","duracion_min":3},{"orden":2,"descripcion":"Disuelve la fécula de maíz en un poco de leche fría.","duracion_min":2},{"orden":3,"descripcion":"Calienta el resto de la leche con el puré de fresa hasta que apenas hierva.","duracion_min":5},{"orden":4,"descripcion":"Agrega la fécula disuelta revolviendo constantemente hasta espesar, suma vainilla y sirve tibio.","duracion_min":5}]'::jsonb,
ARRAY['mexico','latam','atole','fresa','bebida','tradicional'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('pure-aguacate-limon-mexico', 'Puré de aguacate con limón mexicano', 'Versión bebé del guacamole sin chile: aguacate maduro con un toque de limón mexicano. Grasas buenas para el cerebro en desarrollo.', ARRAY['snack','almuerzo'], ARRAY['inicio'], 5, 1, ARRAY[]::text[], 170, 2, 9, 15, 0.5,
'[{"id":"aguacate","nombre":"Aguacate maduro","cantidad":1,"unidad":"unidad","calorias_por_100g":160},{"id":"limon","nombre":"Jugo de limón","cantidad":3,"unidad":"gotas","calorias_por_100g":29},{"id":"cilantro","nombre":"Cilantro picado","cantidad":1,"unidad":"hoja","calorias_por_100g":23}]'::jsonb,
'[{"orden":1,"descripcion":"Parte el aguacate por la mitad y retira el hueso.","duracion_min":1},{"orden":2,"descripcion":"Extrae la pulpa con una cuchara y colócala en un bowl.","duracion_min":1},{"orden":3,"descripcion":"Pisa con tenedor agregando las gotas de limón para que no se oxide.","duracion_min":2},{"orden":4,"descripcion":"Decora con una hojita de cilantro picado muy fino al servir.","duracion_min":1}]'::jsonb,
ARRAY['mexico','latam','aguacate','guacamole-baby','sin-coccion','grasas-buenas','limon'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('compota-mango-tuna-mexico', 'Compota de mango con tuna', 'Compota tropical mexicana con mango y tuna (fruta del nopal). Dulzura natural y vibrante color magenta.', ARRAY['snack','desayuno'], ARRAY['inicio'], 12, 2, ARRAY[]::text[], 90, 1, 22, 0.3, 0.3,
'[{"id":"mango","nombre":"Mango maduro","cantidad":0.5,"unidad":"unidad","calorias_por_100g":60},{"id":"tuna","nombre":"Tuna roja (fruta del nopal)","cantidad":1,"unidad":"unidad","calorias_por_100g":42},{"id":"limon","nombre":"Gotas de limón","cantidad":3,"unidad":"gotas","calorias_por_100g":29}]'::jsonb,
'[{"orden":1,"descripcion":"Pela la tuna roja con cuidado usando guantes (tiene espinitas), retira las semillas con un colador.","duracion_min":5},{"orden":2,"descripcion":"Pela el mango y extrae la pulpa, descartando el hueso.","duracion_min":3},{"orden":3,"descripcion":"Procesa ambas frutas con las gotas de limón hasta lograr una compota lisa.","duracion_min":2},{"orden":4,"descripcion":"Cuela si quedan partes duras y sirve frío o tibio.","duracion_min":2}]'::jsonb,
ARRAY['mexico','latam','tuna','mango','tropical','sin-azucar','color-vibrante'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('crema-elote-dulce-mexico', 'Crema de elote dulce mexicana', 'Crema mexicana clásica con elote tierno, leche y un toque de vainilla. Sabor a fiesta de pueblo, sin epazote para los bebés.', ARRAY['almuerzo','cena'], ARRAY['inicio'], 22, 2, ARRAY['lactosa']::text[], 135, 5, 22, 3.5, 0.6,
'[{"id":"elote","nombre":"Elote tierno desgranado","cantidad":180,"unidad":"g","calorias_por_100g":86},{"id":"leche","nombre":"Leche entera","cantidad":150,"unidad":"ml","calorias_por_100g":61},{"id":"agua","nombre":"Agua","cantidad":100,"unidad":"ml","calorias_por_100g":0},{"id":"vainilla","nombre":"Esencia de vainilla","cantidad":2,"unidad":"gotas","calorias_por_100g":0},{"id":"aceite","nombre":"Aceite","cantidad":3,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Cocina los granos de elote en el agua durante 12 minutos hasta que estén tiernos.","duracion_min":12},{"orden":2,"descripcion":"Procesa el elote con su agua de cocción y la leche hasta obtener una crema suave.","duracion_min":3},{"orden":3,"descripcion":"Devuelve la crema a la olla, agrega aceite y vainilla, cocina 5 minutos más a fuego bajo.","duracion_min":5},{"orden":4,"descripcion":"Cuela si quieres una textura más fina para bebé pequeño.","duracion_min":2}]'::jsonb,
ARRAY['mexico','latam','elote','crema','tradicional','dulce-natural','vegetariano'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('pure-mamey-platano-mexico', 'Puré de mamey con plátano', 'Puré tropical con mamey mexicano, fruta dulce de color rojizo intenso, y plátano. Sin cocción, lleno de antioxidantes.', ARRAY['snack','desayuno'], ARRAY['inicio'], 5, 1, ARRAY[]::text[], 150, 1.8, 36, 0.4, 0.6,
'[{"id":"mamey","nombre":"Mamey maduro","cantidad":100,"unidad":"g","calorias_por_100g":124},{"id":"platano","nombre":"Plátano maduro","cantidad":0.5,"unidad":"unidad","calorias_por_100g":89}]'::jsonb,
'[{"orden":1,"descripcion":"Parte el mamey por la mitad y retira el hueso grande del centro con cuidado.","duracion_min":2},{"orden":2,"descripcion":"Extrae la pulpa rojiza con una cuchara en un bowl.","duracion_min":2},{"orden":3,"descripcion":"Pisa la pulpa de mamey junto con el plátano maduro hasta lograr una crema suave.","duracion_min":1}]'::jsonb,
ARRAY['mexico','latam','mamey','platano','tropical','sin-coccion','antioxidantes'], false, true)
ON CONFLICT (slug) DO NOTHING;

-- ─── TRANSICION (12-23m) — 5 nuevas ──────────────────────────

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('arroz-mexicano-rojo-baby', 'Arroz mexicano rojo baby', 'Arroz rojo clásico mexicano cocinado con tomate, zanahoria y chícharos. Acompañante perfecto sin sal añadida.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 30, 3, ARRAY[]::text[], 200, 5, 38, 3.5, 1.4,
'[{"id":"arroz","nombre":"Arroz blanco","cantidad":100,"unidad":"g","calorias_por_100g":130},{"id":"tomate","nombre":"Tomate maduro","cantidad":120,"unidad":"g","calorias_por_100g":18},{"id":"zanahoria","nombre":"Zanahoria","cantidad":50,"unidad":"g","calorias_por_100g":41},{"id":"chicharos","nombre":"Chícharos (arvejas)","cantidad":40,"unidad":"g","calorias_por_100g":81},{"id":"cebolla","nombre":"Cebolla","cantidad":30,"unidad":"g","calorias_por_100g":40},{"id":"ajo","nombre":"Ajo","cantidad":1,"unidad":"diente","calorias_por_100g":149},{"id":"aceite","nombre":"Aceite","cantidad":8,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Licúa el tomate con la cebolla, el ajo y un poco de agua hasta obtener una salsa lisa.","duracion_min":3},{"orden":2,"descripcion":"Dora el arroz en aceite hasta que tome un tono dorado pálido.","duracion_min":5},{"orden":3,"descripcion":"Agrega la salsa de tomate, los chícharos y la zanahoria rallada. Mezcla.","duracion_min":3},{"orden":4,"descripcion":"Suma agua caliente (el doble del volumen del arroz), tapa y cocina 18 minutos a fuego bajo.","duracion_min":18}]'::jsonb,
ARRAY['mexico','latam','arroz-rojo','iconico','tradicional','acompanante'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('picadillo-norteno-baby-mexico', 'Picadillo mexicano norteño baby', 'Picadillo típico del norte mexicano: carne molida con papa, zanahoria, chícharos y salsa de tomate suave. Plato casero balanceado.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 30, 3, ARRAY[]::text[], 225, 14, 22, 8, 2,
'[{"id":"carne","nombre":"Carne molida magra de res","cantidad":120,"unidad":"g","calorias_por_100g":250},{"id":"papa","nombre":"Papa","cantidad":100,"unidad":"g","calorias_por_100g":77},{"id":"zanahoria","nombre":"Zanahoria","cantidad":60,"unidad":"g","calorias_por_100g":41},{"id":"chicharos","nombre":"Chícharos","cantidad":40,"unidad":"g","calorias_por_100g":81},{"id":"tomate","nombre":"Tomate licuado","cantidad":120,"unidad":"g","calorias_por_100g":18},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"aceite","nombre":"Aceite","cantidad":5,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Dora la cebolla picada fina en aceite hasta transparentar.","duracion_min":4},{"orden":2,"descripcion":"Agrega la carne molida y cocina hasta que pierda el color rosado.","duracion_min":6},{"orden":3,"descripcion":"Suma papa y zanahoria en cubos chiquitos y los chícharos. Mezcla bien.","duracion_min":3},{"orden":4,"descripcion":"Vierte el tomate licuado y un poco de agua. Tapa y cocina 16 minutos hasta que las verduras estén tiernas.","duracion_min":16}]'::jsonb,
ARRAY['mexico','latam','picadillo','norte','tradicional','carne','plato-completo'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('sopa-tortilla-suave-mexico', 'Sopa de tortilla suave', 'Sopa de tortilla mexicana en versión baby: caldo de tomate cremoso con cubitos de tortilla horneada, aguacate y queso fresco.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 28, 2, ARRAY['gluten','lactosa']::text[], 215, 9, 28, 8, 1.4,
'[{"id":"tortillas","nombre":"Tortillas de maíz del día anterior","cantidad":2,"unidad":"unidades","calorias_por_100g":218},{"id":"tomate","nombre":"Tomate maduro","cantidad":200,"unidad":"g","calorias_por_100g":18},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"aguacate","nombre":"Aguacate","cantidad":30,"unidad":"g","calorias_por_100g":160},{"id":"queso-fresco","nombre":"Queso fresco","cantidad":30,"unidad":"g","calorias_por_100g":264},{"id":"agua","nombre":"Agua o caldo de pollo","cantidad":400,"unidad":"ml","calorias_por_100g":0},{"id":"aceite","nombre":"Aceite","cantidad":5,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Corta las tortillas en cubitos pequeños y hornéalos a 180°C por 10 minutos hasta dorar.","duracion_min":12},{"orden":2,"descripcion":"Licúa el tomate con la cebolla y dora la mezcla en aceite durante 5 minutos.","duracion_min":7},{"orden":3,"descripcion":"Agrega el agua o caldo y cocina 8 minutos para integrar sabores.","duracion_min":8},{"orden":4,"descripcion":"Sirve la sopa con los cubitos de tortilla, aguacate en cubitos y queso fresco desmenuzado.","duracion_min":3}]'::jsonb,
ARRAY['mexico','latam','sopa-tortilla','iconico','tradicional','tortilla-horneada'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('tamales-elote-dulces-baby-mexico', 'Tamales de elote dulces baby', 'Tamales mexicanos DULCES de elote tierno (≠ tamales tolimenses colombianos salados): masa cremosa con leche y un toque de panela, en hoja de elote.', ARRAY['snack','desayuno'], ARRAY['transicion'], 50, 4, ARRAY['lactosa']::text[], 195, 5, 36, 4, 1,
'[{"id":"elote","nombre":"Elote tierno desgranado","cantidad":350,"unidad":"g","calorias_por_100g":86},{"id":"leche","nombre":"Leche","cantidad":80,"unidad":"ml","calorias_por_100g":61},{"id":"mantequilla","nombre":"Mantequilla","cantidad":20,"unidad":"g","calorias_por_100g":717},{"id":"panela","nombre":"Panela rallada","cantidad":15,"unidad":"g","calorias_por_100g":380},{"id":"hojas-elote","nombre":"Hojas de elote","cantidad":8,"unidad":"unidades","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Procesa el elote con la leche y la mantequilla derretida hasta obtener una masa amarilla cremosa.","duracion_min":4},{"orden":2,"descripcion":"Mezcla con la panela rallada hasta integrar.","duracion_min":2},{"orden":3,"descripcion":"Lava las hojas de elote y entibialas para que sean flexibles.","duracion_min":3},{"orden":4,"descripcion":"Pon una cucharada de masa en cada hoja, dobla y ata. Cocina en olla con agua durante 35 minutos.","duracion_min":40}]'::jsonb,
ARRAY['mexico','latam','tamales-elote','iconico','tradicional','dulce','vaporizado'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('calabacitas-elote-queso-mexico', 'Calabacitas con elote y queso', 'Calabacitas a la mexicana clásicas: salteadas con elote tierno, tomate y queso fresco que se derrite al final. Comida casera.', ARRAY['almuerzo','cena'], ARRAY['transicion'], 22, 2, ARRAY['lactosa']::text[], 165, 8, 18, 7, 1.2,
'[{"id":"calabacitas","nombre":"Calabacitas mexicanas (zapallo italiano)","cantidad":200,"unidad":"g","calorias_por_100g":17},{"id":"elote","nombre":"Elote desgranado","cantidad":80,"unidad":"g","calorias_por_100g":86},{"id":"tomate","nombre":"Tomate","cantidad":80,"unidad":"g","calorias_por_100g":18},{"id":"queso-fresco","nombre":"Queso fresco","cantidad":40,"unidad":"g","calorias_por_100g":264},{"id":"cebolla","nombre":"Cebolla","cantidad":30,"unidad":"g","calorias_por_100g":40},{"id":"aceite","nombre":"Aceite","cantidad":5,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Corta las calabacitas y el tomate en cubos pequeños.","duracion_min":4},{"orden":2,"descripcion":"Dora la cebolla picada fina hasta transparentar.","duracion_min":4},{"orden":3,"descripcion":"Agrega calabacitas, elote y tomate. Cocina tapado 10 minutos.","duracion_min":10},{"orden":4,"descripcion":"Desmenuza el queso fresco encima y tapa 2 minutos para que se derrita.","duracion_min":4}]'::jsonb,
ARRAY['mexico','latam','calabacitas','a-la-mexicana','tradicional','vegetariano','queso'], false, true)
ON CONFLICT (slug) DO NOTHING;

-- ─── PREESCOLAR (24m+) — 5 nuevas ────────────────────────────

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('mole-suave-bebes-mexico', 'Mole suave para bebés (sin chile picante)', 'Versión baby del mole mexicano: salsa cremosa con chocolate, almendras, sésamo y especias DULCES. SIN chiles picantes.', ARRAY['almuerzo','cena'], ARRAY['preescolar'], 50, 3, ARRAY[]::text[], 295, 18, 22, 14, 2.5,
'[{"id":"pollo","nombre":"Pechuga de pollo cocida","cantidad":150,"unidad":"g","calorias_por_100g":165},{"id":"tomate","nombre":"Tomate","cantidad":100,"unidad":"g","calorias_por_100g":18},{"id":"almendras","nombre":"Almendras peladas","cantidad":20,"unidad":"g","calorias_por_100g":579},{"id":"sesamo","nombre":"Sésamo tostado (ajonjolí)","cantidad":10,"unidad":"g","calorias_por_100g":573},{"id":"chocolate","nombre":"Chocolate amargo 70%","cantidad":15,"unidad":"g","calorias_por_100g":546},{"id":"canela","nombre":"Canela molida","cantidad":1,"unidad":"pizca","calorias_por_100g":247},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"tortilla","nombre":"Tortilla de maíz seca","cantidad":1,"unidad":"unidad","calorias_por_100g":218}]'::jsonb,
'[{"orden":1,"descripcion":"Tuesta levemente almendras y sésamo en sartén seca hasta dorar.","duracion_min":4},{"orden":2,"descripcion":"Licúa tomate, cebolla, almendras, sésamo, tortilla rota, canela y un poco de agua.","duracion_min":3},{"orden":3,"descripcion":"Cocina la salsa licuada 12 minutos a fuego bajo revolviendo.","duracion_min":12},{"orden":4,"descripcion":"Agrega el chocolate rallado, mezcla hasta derretir. Sirve el pollo desmenuzado bañado en mole.","duracion_min":5}]'::jsonb,
ARRAY['mexico','latam','mole','iconico','sin-chile-picante','tradicional','pollo'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('chilaquiles-dulces-baby-mexico', 'Chilaquiles dulces baby', 'Versión baby DULCE de los chilaquiles mexicanos: tortillas horneadas con salsa suave de tomate dulce, queso fresco y crema. SIN chile.', ARRAY['desayuno','almuerzo'], ARRAY['preescolar'], 22, 2, ARRAY['gluten','lactosa']::text[], 245, 11, 28, 10, 1.6,
'[{"id":"tortillas","nombre":"Tortillas de maíz","cantidad":4,"unidad":"unidades","calorias_por_100g":218},{"id":"tomate","nombre":"Tomate maduro","cantidad":200,"unidad":"g","calorias_por_100g":18},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"queso-fresco","nombre":"Queso fresco desmenuzado","cantidad":40,"unidad":"g","calorias_por_100g":264},{"id":"crema","nombre":"Crema fresca","cantidad":30,"unidad":"ml","calorias_por_100g":340},{"id":"aceite","nombre":"Aceite","cantidad":5,"unidad":"ml","calorias_por_100g":884}]'::jsonb,
'[{"orden":1,"descripcion":"Corta las tortillas en triángulos pequeños y hornéalos a 180°C por 12 minutos hasta dorar.","duracion_min":14},{"orden":2,"descripcion":"Licúa tomate con cebolla y un poco de agua, cocina la salsa 6 minutos en aceite.","duracion_min":8},{"orden":3,"descripcion":"Sumerge los triángulos crocantes en la salsa caliente durante 30 segundos.","duracion_min":1},{"orden":4,"descripcion":"Sirve con la crema encima y el queso fresco desmenuzado.","duracion_min":2}]'::jsonb,
ARRAY['mexico','latam','chilaquiles','iconico','sin-chile','tradicional','desayuno-mexicano'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('enchiladas-suizas-suaves-mexico', 'Enchiladas suizas suaves', 'Enchiladas mexicanas suizas en versión baby: tortillas con pollo desmenuzado, bañadas en salsa de tomate verde con crema y queso gratinado. SIN chile.', ARRAY['almuerzo','cena'], ARRAY['preescolar'], 35, 3, ARRAY['gluten','lactosa']::text[], 290, 18, 30, 11, 1.8,
'[{"id":"tortillas","nombre":"Tortillas de maíz","cantidad":4,"unidad":"unidades","calorias_por_100g":218},{"id":"pollo","nombre":"Pechuga de pollo cocida desmenuzada","cantidad":120,"unidad":"g","calorias_por_100g":165},{"id":"tomate-verde","nombre":"Tomate verde (tomatillo)","cantidad":150,"unidad":"g","calorias_por_100g":32},{"id":"cebolla","nombre":"Cebolla","cantidad":40,"unidad":"g","calorias_por_100g":40},{"id":"crema","nombre":"Crema fresca","cantidad":50,"unidad":"ml","calorias_por_100g":340},{"id":"queso","nombre":"Queso para gratinar","cantidad":50,"unidad":"g","calorias_por_100g":264},{"id":"cilantro","nombre":"Cilantro","cantidad":3,"unidad":"hojas","calorias_por_100g":23}]'::jsonb,
'[{"orden":1,"descripcion":"Hierve los tomatillos con la cebolla durante 8 minutos hasta que estén blandos.","duracion_min":10},{"orden":2,"descripcion":"Licúa los tomatillos con cilantro hasta obtener salsa verde lisa y mezcla con la crema.","duracion_min":3},{"orden":3,"descripcion":"Calienta las tortillas, rellena cada una con pollo desmenuzado y enrolla.","duracion_min":6},{"orden":4,"descripcion":"Coloca las enchiladas en fuente, baña con la salsa verde-crema y queso encima. Hornea 15 min a 180°C.","duracion_min":18}]'::jsonb,
ARRAY['mexico','latam','enchiladas','suizas','iconico','sin-chile','horneado','pollo'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('pozole-light-pollo-mexico', 'Pozole light de pollo mexicano', 'Pozole mexicano en versión light: caldo con maíz cacahuazintle (grande), pollo desmenuzado y verduras frescas. SIN chile.', ARRAY['almuerzo','cena'], ARRAY['preescolar'], 50, 3, ARRAY[]::text[], 245, 17, 28, 5, 1.6,
'[{"id":"maiz-pozolero","nombre":"Maíz pozolero cocido (cacahuazintle)","cantidad":150,"unidad":"g","calorias_por_100g":86},{"id":"pollo","nombre":"Pechuga de pollo","cantidad":120,"unidad":"g","calorias_por_100g":165},{"id":"cebolla","nombre":"Cebolla","cantidad":50,"unidad":"g","calorias_por_100g":40},{"id":"ajo","nombre":"Ajo","cantidad":2,"unidad":"dientes","calorias_por_100g":149},{"id":"lechuga","nombre":"Lechuga romana","cantidad":30,"unidad":"g","calorias_por_100g":17},{"id":"rabano","nombre":"Rábano","cantidad":20,"unidad":"g","calorias_por_100g":16},{"id":"limon","nombre":"Limón","cantidad":1,"unidad":"unidad","calorias_por_100g":29},{"id":"agua","nombre":"Agua","cantidad":600,"unidad":"ml","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Hierve el pollo con cebolla y ajo en el agua durante 25 minutos.","duracion_min":25},{"orden":2,"descripcion":"Retira el pollo, desmenúzalo y devuelve el caldo a la olla.","duracion_min":4},{"orden":3,"descripcion":"Agrega el maíz pozolero ya cocido y el pollo desmenuzado, cocina 12 minutos más.","duracion_min":12},{"orden":4,"descripcion":"Sirve con lechuga picada fina, rabanitos rebanados y unas gotas de limón al gusto.","duracion_min":5}]'::jsonb,
ARRAY['mexico','latam','pozole','iconico','sin-chile','tradicional','maiz-cacahuazintle','pollo'], false, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO recetas (slug, nombre, descripcion, momento_dia, etapas_compatibles, tiempo_preparacion, porciones_base, alergenos, calorias, proteinas, carbohidratos, grasas, hierro, ingredientes, pasos, tags, es_premium, activa) VALUES
('pan-muerto-baby-light-mexico', 'Pan de muerto baby light', 'Versión light del icónico pan de muerto mexicano: pan dulce con aroma a azahar y naranja, MUY poca azúcar.', ARRAY['snack','desayuno'], ARRAY['preescolar'], 90, 6, ARRAY['gluten','huevo','lactosa']::text[], 235, 7, 38, 6, 1.5,
'[{"id":"harina","nombre":"Harina de trigo","cantidad":250,"unidad":"g","calorias_por_100g":364},{"id":"levadura","nombre":"Levadura seca","cantidad":7,"unidad":"g","calorias_por_100g":105},{"id":"huevos","nombre":"Huevos","cantidad":2,"unidad":"unidades","calorias_por_100g":155},{"id":"mantequilla","nombre":"Mantequilla blanda","cantidad":50,"unidad":"g","calorias_por_100g":717},{"id":"leche","nombre":"Leche tibia","cantidad":80,"unidad":"ml","calorias_por_100g":61},{"id":"azucar","nombre":"Azúcar mascabo","cantidad":30,"unidad":"g","calorias_por_100g":380},{"id":"naranja","nombre":"Ralladura de naranja","cantidad":1,"unidad":"cucharadita","calorias_por_100g":47},{"id":"agua-azahar","nombre":"Agua de azahar","cantidad":3,"unidad":"gotas","calorias_por_100g":0}]'::jsonb,
'[{"orden":1,"descripcion":"Activa la levadura en la leche tibia con un poco de azúcar durante 8 minutos.","duracion_min":10},{"orden":2,"descripcion":"Mezcla harina, azúcar mascabo, ralladura de naranja, agua de azahar, huevos y mantequilla. Amasa 8 minutos.","duracion_min":12},{"orden":3,"descripcion":"Deja levar tapado en lugar cálido durante 50 minutos hasta que duplique el volumen.","duracion_min":50},{"orden":4,"descripcion":"Forma bollos con decoración de huesitos en la superficie y hornea a 180°C durante 22 minutos.","duracion_min":22}]'::jsonb,
ARRAY['mexico','latam','pan-de-muerto','iconico','tradicional','dia-de-muertos','horneado'], false, true)
ON CONFLICT (slug) DO NOTHING;
